<?php

// ============================================
// WEB ROUTES
// ============================================
// Purpose: Defines all URL routes for the web application
// Each route maps a URL to a controller method
// 
// Route Types:
// - Public routes: Accessible without login
// - Auth routes: Login, register, password reset
// - Protected routes: Require authentication (login)
// ============================================

use App\Http\Controllers\StudentController;
use App\Http\Controllers\DashboardController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

// ============================================
// HOME PAGE (Root Route)
// ============================================
// URL: /
// Method: GET
// Purpose: Redirects based on authentication status
// - If logged in: Goes to dashboard
// - If not logged in: Goes to login page
// ============================================
Route::get('/', function () {
    // Check if user is already logged in
    if (auth()->check()) {
        // User is logged in - go to dashboard
        return redirect()->route('dashboard');
    }
    // User is not logged in - go to login page
    return redirect()->route('login');
});

// ============================================
// AUTHENTICATION ROUTES (Laravel Breeze)
// ============================================
// These routes handle:
// - Login (/login)
// - Register (/register)
// - Password Reset (/forgot-password, /reset-password)
// - Email Verification (/verify-email)
// - Logout (/logout)
// 
// File: routes/auth.php (generated by Breeze)
// ============================================
require __DIR__.'/auth.php';

// ============================================
// PROTECTED ROUTES (Require Authentication)
// ============================================
// All routes in this group require the user to be logged in
// Uses the 'auth' middleware to protect them
// If user is not logged in, they are redirected to /login
// ============================================
Route::middleware(['auth'])->group(function () {
    
    // ============================================
    // DASHBOARD ROUTE
    // ============================================
    // URL: GET /dashboard
    // Controller: DashboardController@index
    // Route Name: dashboard
    // Purpose: Shows dashboard with statistics
    // Access: Only authenticated users (logged in)
    // 
    // Behavior:
    // - Admin: Shows full dashboard with all statistics
    // - Student: Redirects to their own profile page
    // ============================================
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    
    // ============================================
    // STUDENT MANAGEMENT ROUTES (Resource Controller)
    // ============================================
    // URL: /students
    // Controller: StudentController
    // Route Name: students.*
    // Purpose: All CRUD operations for students
    // Access: Only authenticated users (logged in)
    // 
    // Routes Generated by Route::resource():
    // ============================================
    // METHOD   | URL                      | ACTION    | ROUTE NAME
    // ============================================
    // GET      | /students                | index()   | students.index
    // GET      | /students/create         | create()  | students.create
    // POST     | /students                | store()   | students.store
    // GET      | /students/{student}      | show()    | students.show
    // GET      | /students/{student}/edit | edit()    | students.edit
    // PUT/PATCH| /students/{student}      | update()  | students.update
    // DELETE   | /students/{student}      | destroy() | students.destroy
    // ============================================
    // 
    // Access Control (Handled in Controller):
    // - Admin: Full access to all operations
    // - Student: Can only view/edit their own profile
    // ============================================
    Route::resource('students', StudentController::class);
    
    // ============================================
    // PHOTO DELETE ROUTE
    // ============================================
    // URL: DELETE /students/{student}/photo
    // Controller: StudentController@deletePhoto
    // Route Name: students.photo.delete
    // Purpose: Delete only the student's photo (keep the student)
    // Access:
    //   - Admin: Can delete any student's photo
    //   - Student: Can only delete their own photo
    // ============================================
    Route::delete('students/{student}/photo', [StudentController::class, 'deletePhoto'])->name('students.photo.delete');
    
    // ============================================
    // SOFT DELETE / TRASH ROUTES
    // ============================================
    // These routes handle soft deleted (trashed) students
    // All require authentication
    // ============================================
    
    /**
     * TRASHED STUDENTS ROUTE
     * 
     * URL: GET /students/trashed
     * Controller: StudentController@trashed
     * Route Name: students.trashed
     * Purpose: Display all soft-deleted students
     * Access: 
     *   - Admin: Full access
     *   - Student: Redirected with error message
     */
    Route::get('students/trashed', [StudentController::class, 'trashed'])->name('students.trashed');
    
    /**
     * RESTORE STUDENT ROUTE
     * 
     * URL: PATCH /students/{id}/restore
     * Controller: StudentController@restore
     * Route Name: students.restore
     * Purpose: Restore a soft-deleted student
     * Access:
     *   - Admin: Full access
     *   - Student: Redirected with error message
     */
    Route::patch('students/{id}/restore', [StudentController::class, 'restore'])->name('students.restore');
    
    /**
     * FORCE DELETE STUDENT ROUTE
     * 
     * URL: DELETE /students/{id}/force-delete
     * Controller: StudentController@forceDelete
     * Route Name: students.force-delete
     * Purpose: Permanently delete a student
     * Access:
     *   - Admin: Full access
     *   - Student: Redirected with error message
     */
    Route::delete('students/{id}/force-delete', [StudentController::class, 'forceDelete'])->name('students.force-delete');
});

// ============================================
// ROUTE PROTECTION SUMMARY
// ============================================
// 
// PUBLIC ROUTES (No Login Required):
// - /                    → Redirects to login or dashboard
// - /login               → Login page
// - /register            → Registration page
// - /forgot-password     → Password reset request
// - /reset-password/{token} → Password reset form
// - /verify-email        → Email verification
// 
// PROTECTED ROUTES (Login Required):
// - /dashboard                    → Admin dashboard (Admin) or Profile (Student)
// - /students                     → Student list (Admin) or Profile (Student)
// - /students/create              → Create student (Admin only)
// - /students/{id}                → View student (Admin) or Profile (Student)
// - /students/{id}/edit           → Edit student (Admin) or Profile (Student)
// - /students/{id}/photo          → Delete photo (Admin or own profile)
// - /students/trashed             → View trashed students (Admin only)
// - /students/{id}/restore        → Restore student (Admin only)
// - /students/{id}/force-delete   → Permanent delete (Admin only)
// 
// ============================================
// ROUTE NAMING CONVENTIONS
// ============================================
// - All routes use lowercase names
// - Resource routes follow Laravel conventions
// - Route names use dot notation (e.g., students.index)
// - All protected routes are grouped with 'auth' middleware
// ============================================

// ============================================
// ACCESS CONTROL MATRIX
// ============================================
// 
// | Route                     | Admin | Student |
// |---------------------------|-------|---------|
// | /dashboard                | ✅    | ❌ → Profile |
// | /students                 | ✅    | ❌ → Profile |
// | /students/create          | ✅    | ❌ → Error |
// | /students/{id}            | ✅    | ✅ (own only) |
// | /students/{id}/edit       | ✅    | ✅ (own only) |
// | /students/{id}/photo      | ✅    | ✅ (own only) |
// | /students/trashed         | ✅    | ❌ → Error |
// | /students/{id}/restore    | ✅    | ❌ → Error |
// | /students/{id}/force-delete | ✅ | ❌ → Error |
// 
// ============================================